### ISSUE TITLE
Unable to run application in Chrome. - white page appear and browser tab loading

### ISSUE THREAD

**Issue by michaelmok2021** [sfxcode/vite-primevue-starter#20]
Unable to run application in Chrome. - white page appear and browser tab loading. 

In the terninal we get 
![Screenshot from 2021-11-30 09-11-15](https://user-images.githubusercontent.com/77700571/143967875-b1846583-eb3a-406b-ac0e-405e5b76c001.png)

On the browser we get  white page. Our node is v 14.18.1

**Comment by sfxcode** [comment]
Good morning,

the warning above is a primeflex problem. You can ignore this warning, hopefully it will be fixed in the next primeflex version.
Latest node LTS Version: 16 is required. Use node manager like nvm to install.

Hope that will fix your problem.

Greetings,

Tom
