### ISSUE TITLE
globEager is deprecated, causes error

### ISSUE THREAD

**Issue by robinzimmermann** [sfxcode/vite-primevue-starter#80]
In `main.ts`, Visual Code says that `globEager` is deprecated:

<img width="638" alt="image" src="https://github.com/sfxcode/vite-primevue-starter/assets/725660/0c521fdb-3f82-4095-900d-96ab07c19e64">

(Ignore the red squiggle underneath the `i`, but it is annoying that this part of the code is not typed, grr!)

At runtime, the app doesn't start and the following error is in the Javascript console:

<img width="583" alt="image" src="https://github.com/sfxcode/vite-primevue-starter/assets/725660/99b3bee9-36d4-445a-81ba-e3d0f4d2ad6b">

The app fails to load. I started it using `pnpm run dev` from the command line.

**Comment by robinzimmermann** [comment]
(BTW, thank you for an excellent starter project template!)

**Comment by robinzimmermann** [comment]
I have temporarily worked around the issue:

```js
// register vue composition api globally
import { ViteSSG } from "vite-ssg";
import generatedRoutes from "virtual:generated-pages";
import { setupLayouts } from "virtual:generated-layouts";
import App from "./App.vue";
import "uno.css";
import "@sfxcode/formkit-primevue/dist/sass/formkit-primevue.scss";
const modules = import.meta.glob("./modules/*.ts", { eager: true });

const routes = setupLayouts(generatedRoutes);

export const createApp = ViteSSG(App, { routes }, (ctx) => {
  // install all modules under `modules/`
  Object.values(modules).map((i: any) => i.install?.(ctx));
});
```

- I added line 8: `const modules = import.meta.glob("./modules/*.ts", { eager: true });`,
- and modified line 14: `Object.values(modules).map((i: any) => i.install?.(ctx));`

But I have no idea what the correct solution should be.

**Comment by sfxcode** [comment]
Good morning Robin,

try to fix with latest release. Please give it a try to see if it solves your problem.

Greetings, Tom

**Comment by robinzimmermann** [comment]
I believe it's working, thank you for the quick response!

**Comment by robinzimmermann** [comment]
(I'm not sure if I should close the ticket or let someone else do it...)
